# Generated by Django 2.0.6 on 2018-06-25 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("rating", models.CharField(choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")], max_length=1)),
                ("title", models.CharField(max_length=64)),
                ("summary", models.CharField(max_length=10000)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="reviews.Company")),
                ("reviewer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
